name: GitHub Actions Quickstart

# 이벤트 트리거: 코드가 원격 저장소에 Push될 때 실행
on: [push]

jobs:
  Explore-GitHub-Actions:
    # 실행 환경: 최신 우분투 서버 사용
    runs-on: ubuntu-latest

    steps:
      # 작업 1: 텍스트 출력
      - name: Print Hello Message
        run: echo "Hello, GitHub Actions!"

      # 작업 2: 실행 중인 서버의 운영체제 정보 확인
      - name: Check OS Info
        run: cat /etc/os-release
